services:
  slot-finder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simply-book-it-slot-finder
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=PRODUCTION
    networks:
      - docker-default
networks:
  docker-default:
    name: docker-default
    external: true